dist: focal

language: python

python:
  - "3.8"

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0

services: 
  - xvfb
  - mysql

env:
  global:
   - API_PATH=docs/source/api

cache: 
 - directories:
   - $HOME/.cache/pip

before_install:
  - sudo apt-get -y install python3-pyqt5.qtsql python3-pytestqt python3-pytest-cov python3-numpy

install: 
  - pip install -U pip
  - pip install nibabel pandas wonambi bidso
  - pip install codecov 
  - pip install -e .

script:
  - pytest-3 tests/ -vv

after_success:
  - codecov

notifications:
  email: false
