language: python

python:
 - "3.7"

addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0
    - python3-pyqt5.qtsql
    - libqt5sql5-mysql

  mariadb: '10.3'

services: xvfb

dist: bionic

env:
  global:
   - API_PATH=docs/source/api
   - DOCTREES_PATH=docs/build/doctrees
   - HTML_PATH=docs/build/html

cache: 
 - directories:
   - $HOME/.cache/pip

install: 
  - pip install -U pip
  - pip install -U numpy
  - pip install nibabel pandas wonambi bidso
  - pip install -U pytest pytest-cov pytest-qt codecov 
  - pip install -U sphinx 
  - pip install -e .

before_scripts:
  - sudo mysql -e "create user giovanni@localhost IDENTIFIED BY 'password';"
  - sudo mysql -e 'grant all on test2.* to giovanni@localhost;'

script:
  - pytest --cov=xelo2 tests/ -vv
  - sphinx-apidoc -f -M -E -o $API_PATH xelo2
  - sed -zi "s/Submodules\n----------\n//g" $API_PATH/*.rst
  - sphinx-build -d $DOCTREES_PATH docs/source/ $HTML_PATH

after_success:
  - codecov

notifications:
  email: false

deploy:
 - provider: pages
   skip_cleanup: true
   local_dir : $HTML_PATH
   repo : gpiantoni/xelo2
   target_branch : gh-pages
   github_token : $GITHUB_TOKEN
