services:

language: python

python:
  - "3.7"

addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0

services: 
  - xvfb
  - mysql

dist: bionic

env:
  global:
   - API_PATH=docs/source/api

cache: 
 - directories:
   - $HOME/.cache/pip

install: 
  - pip install -U pip
  - pip install -U numpy
  - pip install PyQt5 nibabel pandas wonambi bidso
  - pip install -U pytest pytest-cov pytest-qt codecov 
  - pip install -e .

script:
  - pytest --cov=xelo2 tests/ -vv

after_success:
  - codecov

notifications:
  email: false
